language: objective-c
osx_image: xcode7.2
before_install:
- curl -L -O https://github.com/Carthage/Carthage/releases/download/0.15/Carthage.pkg
- sudo installer -pkg Carthage.pkg -target /
install: true
script: carthage bootstrap --platform iOS
